hardwarehelper web desgin
zsimjee/hardwarehelper pull request #1
Opened 2017-12-05 20:06 UTC by hsimjee

Design the basics for the website. We will need to do more work on it once we figure out the store.

2017-12-08 18:40 UTC, zsimjee requested changes
Yeah please clean this up. I don't know why we're using materialize... don't really see what it buys us. I think we can do this using just jquery+bootstrap.

Also, collapse similar commits. You've posted a review request for 27 commits... I don't see why...

2017-12-08 18:40 UTC, zsimjee commented on index.html
> +<!DOCTYPE html>
why was this necessary to move to a diff file? Instead, why not have an index.html with a nav, and the cabinets.html should be one of the items in the nav

2017-12-08 18:40 UTC, zsimjee commented on js/init.js
> +(function($){
why...

also, if we do have a js bucket, we should refactor the knapsack formula into it from cabinets.html

2017-12-08 18:40 UTC, zsimjee commented on js/init.js
> +    $('.button-collapse').sideNav();
we shouldn't need this

2017-12-08 18:40 UTC, zsimjee commented on js/init.js
> +    $('.parallax').parallax();
I don't like parallax

2017-12-08 18:40 UTC, zsimjee commented on js/materialize.js
> +var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false;
Why would you make the choice to import this file vs link to it via CDN? Why is this a necessary dependency in the first place?

2017-12-08 18:40 UTC, zsimjee commented on js/materialize.min.js
> +function _classCallCheck(t,e){if(!(t instanceof e))throw new TypeError("Cannot call a class as a function")}var _createClass=function(){function t(t,e){for(var i=0;i<e.length;i++){var n=e[i];n.enumer
same as above

2018-03-05 23:34 UTC, hsimjee commented
Merged commits together and have the basic website designed. Waiting for the backend to implement the store.

2018-03-09 03:34 UTC, hsimjee commented
added a loader as well and made UI changes

2018-03-09 03:37 UTC, zsimjee approved these changes

2018-03-09 03:38 UTC, zsimjee approved these changes

2018-03-09 03:39 UTC, merged